baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "The Chowington Blog"
theme = "lightbi" 
metaDataFormat = "yaml"
pygmentsStyle = "trac"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2 January"
comments = false
readingTime = true
wordCount = true
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = false
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = true
authorInfo = "Fooding?"
description="Foooooooooooooooooofa"
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Chow"
  email = "sample@gmail.com"
  instagram = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


